### ISSUE TITLE
Aligning photos on page

### ISSUE THREAD

**Issue by IndianGuru** [gopherconindia/gopherconindia.github.io#748]
Please align the photos on the page http://www.gophercon.in/individuals/

**Comment by kpvarma** [comment]
@SatishTalim Images are aligned. If we can get a better image of Dave Cheney, we could have all the images in similar size.

**Comment by IndianGuru** [comment]
![dave cheney](https://cloud.githubusercontent.com/assets/178281/8349877/25f49b82-1b3e-11e5-9d0f-a1a381606bed.jpg)
