### ISSUE TITLE
Add Sidu Ponnappa

### ISSUE THREAD

**Issue by IndianGuru** [gopherconindia/gopherconindia.github.io#749]
Add Sidu Ponnappa in the top row - http://www.gophercon.in/staff-information/

https://twitter.com/ponnappa

![sidu](https://cloud.githubusercontent.com/assets/178281/8347249/69df22ba-1b23-11e5-9a42-780a24e3b714.jpg)

**Comment by kpvarma** [comment]
@SatishTalim  Phone Number Missing

**Comment by IndianGuru** [comment]
Added
