### ISSUE TITLE
AeroSpike image at two places not looking good

### ISSUE THREAD

**Issue by IndianGuru** [gopherconindia/gopherconindia.github.io#751]
http://www.gophercon.in/supporters/

and

on the main page under supporters

The logos have been sent to you by email

**Comment by kpvarma** [comment]
@SatishTalim 

I have a .eps format of AeroSpike which you have send last time.
Have you send it recently ?

I would need a graphics guy to convert .eps to png/jpeg otherwise.

**Comment by IndianGuru** [comment]
![aerospike_png](https://cloud.githubusercontent.com/assets/178281/8846765/0ff6ad74-3147-11e5-8b42-19e8eb89e37b.png)

**Comment by kpvarma** [comment]
Thank you. This will be done by EOD

**Comment by IndianGuru** [comment]
Aerospike image on http://www.gophercon.in/supporters/
 not clear
