### ISSUE TITLE
Ardan Labs image on main page under Supporters - change and align

### ISSUE THREAD

**Issue by IndianGuru** [gopherconindia/gopherconindia.github.io#752]
Ardan Labs image on main page under Supporters - change and align

**Comment by kpvarma** [comment]
Do you want to just align the Ardan Labs Image or change it ?
If we have to change it we will have to get the new logo

**Comment by IndianGuru** [comment]
I just want it properly aligned.

**Comment by kpvarma** [comment]
okie It will be done by EOD

**Comment by prakash89** [comment]
Fixes #752 and #751
