### ISSUE TITLE
GopherConIndia 2015 Photos and Videos link

### ISSUE THREAD

**Issue by IndianGuru** [gopherconindia/gopherconindia.github.io#755]
When the GopherCon 2015 menu is active; have 3 sub menus - Site | Photos | Videos

The Photos link is -
https://plus.google.com/photos/110396546927072297938/albums/6120386773375892385

The Videos link is -
https://www.youtube.com/playlist?list=PLxFC1MYuNgJTY3uQ5Ja4F5Sz305nnrBOq

**Comment by IndianGuru** [comment]
Krishna look at http://rubyconf.org/ Go to the bottom of the page and we have a link to About RubyConf - if you click then it takes you to a new page http://rubyconf.org/about.html which has links to videos/photos/2015 etc - can we do the same for GopherCnIndia?

**Comment by prakash89** [comment]
We added Gallery link in footer, if we click then it takes us to new page which has link to videos and photos. please check it and if we have any changes please let us known. Thanks.

**Comment by IndianGuru** [comment]
Yes looks good. The links to Photos and Videos are above.

Now the questions remains as to where do we give a link to the 2015 site i.e. gophercon.in/2015 ?

**Comment by prakash89** [comment]
we added 2015 link in 2016 site please check https://github.com/gopherconindia/gopherconindia.github.io/pull/762 PR.

If we have any changes please let us known.

**Comment by IndianGuru** [comment]
a. I am not happy of the placement of the GopherConIndia 2015 link
b. I am also not happy of the look-and-feel of the Gallery page

Let's discuss this once Krishna is back next week (i.e. 7th Sept onwards).

**Comment by kpvarma** [comment]
I spoke to Prakash, He is working on it.

**Comment by prakash89** [comment]
Can u please check https://github.com/gopherconindia/gopherconindia.github.io/pull/763 PR.
I removed 2015 link in home page and added under about page and also change look and feel of gallery page.

Please let me know if we have any changes.

**Comment by IndianGuru** [comment]
Prakash - it's now looking good. 
Gallery looking good.
One change - change "Post Conference" (at 2 places) to "Past Conferences".

**Comment by prakash89** [comment]
Changed "Post Conference" to "Past Conferences". 

Please check https://github.com/gopherconindia/gopherconindia.github.io/pull/764 PR.

**Comment by IndianGuru** [comment]
All okay now.
