### ISSUE TITLE
Activate 2016 site please

### ISSUE THREAD

**Issue by IndianGuru** [gopherconindia/gopherconindia.github.io#767]
Krishna, have copied the 2016 site to a sub folder 2016 - please activate the same asap.

**Comment by vjdhama** [comment]
@IndianGuru I'm trying to refactor the site. I'll fix the front page and 2016 site first. Might take a while.

**Comment by IndianGuru** [comment]
Ok no issue. Thanks.

**Comment by vjdhama** [comment]
2016 site is working, hence I am closing this. If there is a specific issue, please create a new issue. Feel free to reopen this, if you think otherwise.

**Comment by IndianGuru** [comment]
The menu for the 2016 site is incomplete.

**Comment by vjdhama** [comment]
@IndianGuru I have fixed 2016 site nav header. Let me know if you happen find a issue with 2016 site.
