### ISSUE TITLE
Modifying a page screwed up the 2016 page also

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#811]
Modifying page http://www.gophercon.in/talk-schedule/ screwed up the page http://www.gophercon.in/2016/talk-schedule/

**Comment by prathamesh-sonpatki** [comment]
Fixed it. Please check http://www.gophercon.in/talk-schedule/ and http://www.gophercon.in/2016/talk-schedule/

**Comment by smtalimett** [comment]
Awesome!!
