### ISSUE TITLE
Add Oogway as Gold Sponsor

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#825]
Logo from DeccanRubyConf site - asked Nishant to send write up.

**Comment by prathamesh-sonpatki** [comment]
http://www.gophercon.in/talk-schedule/ updated. once we get the write up, will update home page.

**Comment by smtalimett** [comment]
Image: http://www.deccanrubyconf.org/assets/images/sponsors/oogway.png

[Oogway Consulting](http://oogway.in/) is a Pune based software and technology consulting company that focuses on scalability, reliability and relevance of software solutions.

With a belief that there is no secret ingredient we help our customers identify and solve real world problems. Rational thought and first principles feature prominently in our toolset.

The team loves solving problems, coffee, Kung Fu Panda and Pune. 

![oogway_logo](https://cloud.githubusercontent.com/assets/18298741/21952069/c2d7a1aa-da38-11e6-8ef1-63a45f5c18eb.png)
