### ISSUE TITLE
scholarship section is not updated

### ISSUE THREAD

**Issue by nikhita** [gopherconindia/gopherconindia.github.io#884]
There is no scholarship section on the website. But the AirTable link exists now: https://airtable.com/shrAlNa8SEWy6WFbL.

I wanted to ask some people to apply. Would be nice to have the information on the website. :)

**Comment by nikhita** [comment]
Also, the description on the AirTable link says committee will "evaluate code". I think this description is from 2016?

There is confusion among students if they need to complete some assignment to apply for the scholarship.

**Comment by nikhita** [comment]
cc @smtalimett

**Comment by prathamesh-sonpatki** [comment]
@nikhita Should be good now http://www.gophercon.in/scholarship/ Thanks :)

**Comment by nikhita** [comment]
@prathamesh-sonpatki Thanks for the quick fix! :)
