### ISSUE TITLE
Add Niranjan Paranjape as a Speaker for GCI18

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#908]
Talk on Zen And The Art of Software Development

**Comment by prathamesh-sonpatki** [comment]
@smtalimett Please add bio and profile pic.

**Comment by smtalimett** [comment]
![niranjan-paranjape](https://user-images.githubusercontent.com/18298741/33256368-cacd3d46-d377-11e7-8def-4377ae45f17b.jpeg)

Niranjan Paranjape, CTO, GO-JEK
