### ISSUE TITLE
Add Sean Kelly as a Speaker

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#910]
Sean Kelly (affectionately known as Stabby) is a Lead Software Engineer and Engineering Manager for Rapid7. A simple man with a dog for an avatar, he enjoys learning new things, helping / mentoring others, and posting photos of his dog on the internet. When he's not giving talks, he enjoys spending time at home with his wife, taking his dog to the park, and coming up with new projects to work on that he will never actually finish.

![speakershot](https://user-images.githubusercontent.com/18298741/33788887-e5d3769c-dc9a-11e7-9cc0-be0cb7aa733c.jpg)

His talk is on Embedding

**Comment by prathamesh-sonpatki** [comment]
what is his twitter handle?

**Comment by smtalimett** [comment]
Twitter id is https://twitter.com/StabbyCutyou
