### ISSUE TITLE
Add Rishi Shah as a new speaker

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#914]
Rishi is working as a Platform Engineer at Directi. In the past, he worked with CERN to implement new data transfer system for CMS experiment at the Large Hadron Collider. Nowadays he is writing a book on the practical use case of Elasticsearch database.

Profile photo - https://goo.gl/7EUY4Z

Talk: De-centralize Data replication and bookkeeping system

**Comment by prathamesh-sonpatki** [comment]
@smtalimett  What is his twitter handle?

**Comment by smtalimett** [comment]
His Twitter profile is https://twitter.com/rishiloyola
