### ISSUE TITLE
Add Mahadevan Ramachandran as a new Speaker

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#915]
![photo](https://user-images.githubusercontent.com/18298741/33935548-5788ffac-e022-11e7-8627-301ea45d82a6.jpg)

Mahadevan Ramachandran is the technical co-founder and CEO of RapidLoop. In his career spanning more than 18 years, he has co-founded RapidLoop, a startup that creates cloud native solutions for server monitoring, database monitoring, service monitoring and app metric monitoring. He also served as game CTO for top Zynga titles (including Draw Something, Hidden Chronicles, ChefVille) reaching millions of players and led the engineering team that built and launched the first Zynga title from India (Hidden Shadows). Previously Mahadevan led development teams creating products for global businesses at Siemens, Philips, Emulex and EMC. He released his first FOSS in the early ‘90s - to India’s first BBS (CiX) and continues to be an active open source contributor.

His talk is on "Writing Job Queues in Go"

**Comment by prathamesh-sonpatki** [comment]
@smtalimett What is his twitter handle?

**Comment by smtalimett** [comment]
His twitter handle is https://twitter.com/mdevanr
