### ISSUE TITLE
Add new speaker Rushabh Dadbhawala

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#919]
Rushabh is solving problems using software since 15 years. He is well grounded in Object Orientation, Design Patterns and Software Architecture. He is both domain and technology agnostic; “tightly coupled” only to source code! At Continuum, Rushabh works with multiple teams to build the new product platform. Rushabh prefers to roll up the sleeves and get hands dirty with code. He is not what one would call a "white board architect".

![rushabh](https://user-images.githubusercontent.com/18298741/34477519-ad05415e-efc0-11e7-98c1-ebda8ddbc003.jpg)

**Comment by prathamesh-sonpatki** [comment]
@smtalimett Please let me know what is his twitter handle.

**Comment by smtalimett** [comment]
He does not use Twitter
