### ISSUE TITLE
GCI18 site loads GCI19 site

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#971]

**Comment by prathamesh-sonpatki** [comment]
@IndianGuru Can you elaborate on this?

**Comment by smtalimett** [comment]
Example click on Past Conferences and then on 2018 it takes one to https://gopherconindia.com/2018/ which contains 2019 site.

![marriott](https://user-images.githubusercontent.com/18298741/44716595-69d49f00-aad8-11e8-9780-6d2ee5f61488.jpg)

**Comment by prathamesh-sonpatki** [comment]
@SwatiJadhav46 Please close this if fixed
