### ISSUE TITLE
GCI19 venue is not mentioned on site

### ISSUE THREAD

**Issue by smtalimett** [gopherconindia/gopherconindia.github.io#972]
Resort Rio, Goa on 18-19 Jan. 2019

**Comment by smtalimett** [comment]
Also, every link takes to the GCI18 site for example on the main page if anyone clicks on Register he/she is taken to the 2018 site namely https://gopherconindia.com/registration-information/

**Comment by prathamesh-sonpatki** [comment]
The link is correct. The information on that page needs to be updated for 2019.

The page is from 2018 site only if it has 2018 in the URL. Otherwise it is 2019 site.

**Comment by prathamesh-sonpatki** [comment]
@SwatiJadhav46 Please close this if fixed
